stages:
    - install
    - compile_default
    - run_default
    - compile_picsar
    - run_picsar
    - compile_debug
    - compile_no_mpi_threadmultiple
    - compile_no_openmp

install:
  stage: install
  only:
    - develop
    - develop-mat

  script:
    # Force workdir cleaning in case of retried
    - echo "CI_PIPELINE_ID = " $CI_PIPELINE_ID
    - env
    - if [ -d /sps/gitlab-runner/$CI_PIPELINE_ID ] ; then rm -rf /sps/gitlab-runner/$CI_PIPELINE_ID ; fi
    # Move in test dir
    - mkdir -p /sps/gitlab-runner/$CI_PIPELINE_ID
    - cp -r $CI_PROJECT_DIR /sps/gitlab-runner/$CI_PIPELINE_ID
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei
    # Set the environment
    - make uninstall_happi
    - make happi

compile_default:
  stage: compile_default
  only:
    - develop
    - develop-mat

  script:
    # Move in test dir
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -c  -v -l "/sps/gitlab-runner/logs" -t "00:30:00"

run1D:
  stage: run_default
  only:
    - develop
    - develop-mat

  script:
    # Move in test dir
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -b "tst1d_*_*.py" -m 4 -o 4 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst_ionization_current_1d*.py" -m 4 -o 4 -v -r 1 -l "/sps/gitlab-runner/logs"

run2D:
  stage: run_default
  only:
    - develop
    - develop-mat


  script:
    # Move in test dir
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -b "tst2d_??_*.py" -m 4 -o 4  -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst2d_s_??_*.py" -m 4 -o 4 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst2d_v_??_*.py" -m 4 -o 4 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst_ionization_current_2d*.py" -m 4 -o 4 -v -r 1 -l "/sps/gitlab-runner/logs"

# run3D:
#   stage: run_default
#   only:
#     - develop
#     - develop-mat
#
#   script:
#     # Move in test dir
#     - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
#     # Run validation script
#     - python validation.py -b "tst3d_??_*.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
#     - python validation.py -b "tst3d_s_??_*.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
#     - python validation.py -b "tst3d_v_??_*.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
#     - python validation.py -b "tst3d_a_??_*.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
#     - python validation.py -b "tst_ionization_current_3d*.py" -m 4 -o 4 -v -r 1 -l "/sps/gitlab-runner/logs"

run_3d_scalar:
  stage: run_default
  only:
    - develop
    - develop-mat

  script:
    # Move in test dir
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script

    - python validation.py -b "tst3d_04_laser_wake_lehe.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_13_particle_injection_x.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_18_synchrotron_analytical.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_10_em_propagation_external_field_tabulated.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_04_laser_wake.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_16_envelope_propagation_reduced_dispersion.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_07_envelope_propagation.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_17_envelope_wake_reduced_dispersion.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_11_laser_offset.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_08_envelope_wake.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_12_relativistic_electron_beam_field_initialization.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_14_electron_sphere_field_initialization.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_06_profiles.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_13_particle_injection_y.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_04_laser_wake_sdmd.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_02_diags.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_09_relativistic_cylindrical_bunch.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_13_particle_injection_z.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_00_em_propagation.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_21_z_laser_offset.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_20_y_em_propagation.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"

    - python validation.py -b "tst3d_s_o2_laser_wake_yee_vay.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_s_o2_thermal_plasma.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_s_o2_synchrotron_radiation_chi1.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_s_o2_laser_wake_yee_higuera.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_s_o4_thermal_plasma.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"

    - python validation.py -b "tst_ionization_current_3d*.py" -m 4 -o 4 -v -r 1 -l "/sps/gitlab-runner/logs"

run_3d_vecto:
  stage: run_default
  only:
    - develop
    - develop-mat

  script:
    # Move in test dir
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -b "tst3d_v_??_*.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"
    - python validation.py -b "tst3d_a_??_*.py" -m 8 -o 12 -v -r 1 -l "/sps/gitlab-runner/logs"

runAM:
  stage: run_default
  only:
    - develop
    - develop-mat


  script:
    # Move in test dir
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -b "tstAM_??_*.py" -m 8 -o 12 -v -t 00:30:00 -l "/sps/gitlab-runner/logs"

runCollisions:
  stage: run_default
  only:
    - develop
    - develop-mat

  script:
    # Move in test dir
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run checking script
    - python validation.py -b "tst_collisions*.py" -m 4 -o 4 -v -r 1 -l "/sps/gitlab-runner/logs"

compile_picsar:
  stage: compile_picsar
  only:
    - develop

  script:
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei
    - make clean
    - python validation/validation.py -k picsar -c -v

run_picsar:
  stage: run_picsar
  only:
    - develop

  script:
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    - python validation.py -k picsar -b "tstAM_picsar_04_laser_wake.py" -m 4 -o 4 -v

compile_debug:
  stage: compile_debug
  only:
    - develop
    - develop-mat

  script:
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei
    - make clean
    - python validation/validation.py -k debug -c -v

compile_no_mpi_threadmultiple:
  stage: compile_no_mpi_threadmultiple
  only:
    - develop
    - develop-mat

  script:
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei
    - make clean
    - python validation/validation.py -k no_mpi_tm -c -v

compile_no_openmp:
  stage: compile_no_openmp
  only:
    - develop
    - develop-mat


  script:
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei
    - make clean
    - python validation/validation.py -k noopenmp -c -v
