stages:
    - compile
    - makerun

compile:
  stage: compile
  only:
    - develop
    - develop_validation

  script:
    # Move in test dir
    - mkdir /sps/gitlab-runner/$CI_PIPELINE_ID
    - cp -r $CI_PROJECT_DIR /sps/gitlab-runner/$CI_PIPELINE_ID
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run checking script
    - python validation.py -c  -v

makerun1D:
  stage: makerun
  only:
    - develop
  script:
    # Move in test dir
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run checking script
    - python validation.py -b "tst1d_*_*.py" -s all -m 4 -o 4 -v

makerun2D:
  stage: makerun
  only:
    - develop
  script:
    # Move in test dir
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run checking script
    - python validation.py -b "tst2d_*_*.py" -s all -m 4 -o 4  -v

makerun3D:
  stage: makerun
  only:
    - develop
  script:
    # Move in test dir
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run checking script
    - python validation.py -b "tst3d_*_*.py" -s all -m 16 -o 12 -v

advanced_validation:
  stage: makerun
  only:
    - develop_validation
  script:
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    - python validation.py -b tst1d_0_em_propagation.py -m 4 -o 4  -v


