stages:
    - compile
    - makerun

compile:
  stage: compile
  only:
    - develop
    - radiationSpectrum

  script:
    # Force workdir cleaning in case of retried
    - echo "CI_PIPELINE_ID = " $CI_PIPELINE_ID
    - env
    - if [ -d /sps2/gitlab-runner/$CI_PIPELINE_ID ] ; then rm -rf /sps2/gitlab-runner/$CI_PIPELINE_ID ; fi
    # Move in test dir
    - mkdir -p /sps2/gitlab-runner/$CI_PIPELINE_ID
    - cp -r $CI_PROJECT_DIR /sps2/gitlab-runner/$CI_PIPELINE_ID
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei
    # Set the environment
    - make uninstall_happi
    - make happi
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -c  -v

makerun1D:
  stage: makerun
  only:
    - develop
    - radiationSpectrum

  script:
    # Move in test dir
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -b "tst1d_*_*.py" -m 4 -o 4 -v -r 1

makerun2D:
  stage: makerun
  only:
    - develop
    - radiationSpectrum

  script:
    # Move in test dir
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -b "tst2d_*_*.py" -m 4 -o 4  -v -r 1

makerun3D:
  stage: makerun
  only:
    - develop
    - radiationSpectrum

  script:
    # Move in test dir
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -b "tst3d_??_*.py" -m 4 -o 4 -v -r 1

makerunAM:
  stage: makerun
  only:
    - develop
    - radiationSpectrum

  script:
    # Move in test dir
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -b "tstAM_??_*.py" -m 4 -o 4 -v

makerunV:
  stage: makerun
  only:
    - develop
    - radiationSpectrum

  script:
    # Move in test dir
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -b "tst?d_v_??_*.py" -m 4 -o 4 -v -r 1

makerunCollisions:
  stage: makerun
  only:
    - develop
    - radiationSpectrum

  script:
    # Move in test dir
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run checking script
    - python validation.py -b "tst_collisions*.py" -m 4 -o 4 -v -r 1
