stages:
    - compile
    - makerun
    - use_picsar

compile:
  stage: compile
  only:
    - develop
    - merge_sdmd_dev

  script:
    # Force workdir cleaning in case of retried
    - echo "CI_PIPELINE_ID = " $CI_PIPELINE_ID
    - env
    - if [ -d /sps2/gitlab-runner/$CI_PIPELINE_ID ] ; then rm -rf /sps2/gitlab-runner/$CI_PIPELINE_ID ; fi
    # Move in test dir
    - mkdir -p /sps2/gitlab-runner/$CI_PIPELINE_ID
    - cp -r $CI_PROJECT_DIR /sps2/gitlab-runner/$CI_PIPELINE_ID
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei
    # Set the environment
    - make uninstall_happi
    - make happi
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    #- python validation.py -c  -v

makerun1D:
  stage: makerun
  only:
    - develop
    #- merge_sdmd_dev

  script:
    # Move in test dir
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -b "tst1d_*_*.py" -m 4 -o 4 -v -r 1

makerun2D:
  stage: makerun
  only:
    - develop
    #- merge_sdmd_dev

  script:
    # Move in test dir
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -b "tst2d_*_*.py" -m 4 -o 4  -v -r 1

makerun3D:
  stage: makerun
  only:
    - develop
    #- merge_sdmd_dev

  script:
    # Move in test dir
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -b "tst3d_??_*.py" -m 4 -o 4 -v -r 1

makerunAM:
  stage: makerun
  only:
    - develop
    #- merge_sdmd_dev

  script:
    # Move in test dir
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -b "tstAM_??_*.py" -m 4 -o 4 -v

makerunV:
  stage: makerun
  only:
    - develop
    #- merge_sdmd_dev

  script:
    # Move in test dir
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run validation script
    - python validation.py -b "tst?d_v_??_*.py" -m 4 -o 4 -v -r 1

makerunCollisions:
  stage: makerun
  only:
    - develop
    #- merge_sdmd_dev
    
  script:
    # Move in test dir
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    # Run checking script
    - python validation.py -b "tst_collisions*.py" -m 4 -o 4 -v -r 1

use_picsar:
  stage: use_picsar
  only:
    - merge_sdmd_dev

  script:
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei
    - make clean
    - module load fftw/3.3.7-opm-1.6.5-icc-17
    - ls /home/llr/galop/derouil/applications/picsar/lib
    - export LIBPXR=/home/llr/galop/derouil/applications/picsar/lib
    - export LD_LIBRARY_PATH=$LIBPXR:$LD_LIBRARY_PATH
    - cd /sps2/gitlab-runner/$CI_PIPELINE_ID/smilei/validation
    - python validation.py -c -v -k picsar
