stages:
    - compile
    - makerun1D
    - makerun2D
    - makerun3D

compile:
  stage: compile
  only:
    - CI
  script:
    # Move in test dir
    - mkdir /sps/gitlab-runner/$CI_PIPELINE_ID
    - cp -r $CI_PROJECT_DIR /sps/gitlab-runner/$CI_PIPELINE_ID
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/scripts
    # Run checking script
    - python validation.py -c  -v

makerun1D:
  stage: makerun1D
  only:
    - CI
  script:
    # Move in test dir
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/scripts
    # Run checking script
    - python validation.py -b "tst1d_*_*.py" -s all -v

makerun2D:
  stage: makerun2D
  only:
    - CI
  script:
    # Move in test dir
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/scripts
    # Run checking script
    - python validation.py -b "tst2d_*_*.py" -s all -v

makerun3D:
  stage: makerun3D
  only:
    - CI
  script:
    # Move in test dir
    - cd /sps/gitlab-runner/$CI_PIPELINE_ID/smilei/scripts
    # Run checking script
    - python validation.py -b "tst3d_*_*.py" -s all -m 16 -o 8 -v

#test:
#  stage: test
#  only:
#    - master
#    - develop
#  script:
#    - make clean install unit_test
#
#doc_develop:
#  stage: doc
#  only:
#    - develop
#  script:
#    - make clean install
#    - make -C docs
#
#doc_master:
#  stage: doc
#  only:
#    - master
#  script:
#    - make clean install
#    - make -C docs
#    - rsync -rL docs/documentation/html/* pyrame@llr.in2p3.fr:/home/llr/info/www/sites/pyrame/documentation
#
#web_master:
#  stage: web
#  only:
#    - master
#  script:
#    - rsync -rL exclude_from_packaging/www/* pyrame@llr.in2p3.fr:/home/llr/info/www/sites/pyrame/
#
#publish_master:
#  stage: publish
#  only:
#    - tags
#  script:
#    - make tarball
#    - scp pyrame.tgz pyrame@llr.in2p3.fr:/home/llr/info/www/sites/pyrame/pyrame_${CI_BUILD_TAG}.tgz
#    - rm pyrame.tgz
#
#uninstall:
#  stage: uninstall
#  only:
#    - master
#    - develop
#  script:
#    - make uninstall
#  when: always
