os: linux

install: make get-deps

language: cpp

sudo: required

dist: trusty

before_install:
  - cat .travis.yml
  - sudo apt-get -qq update
  - sudo apt-get install -y libopenmpi-dev

script:
  - git checkout -b travis
  - git tag -a v1.0 -m "travis 1.0"
  - make

install:
