os: linux

language: python

install:

git:
  depth: 9999999

before_install:
  - git fetch -t
  - pip install Sphinx alabaster

script:
 - make doc
 - touch build/html/.nojekyll
 - mkdir -p build/html/_downloads
 - for v in `git tag | grep '^v'`; do  git archive -o build/html/_downloads/smilei-${v}.tar.gz $v; done

deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GH_TOKEN
 keep-history: true
 local-dir: build/html
 on:
   branch: master



