os: linux

install: make get-deps

language: cpp

sudo: required

dist: trusty

git:
  depth: 9999999

before_install:
  - sudo apt-get -qq update
  - git fetch -t
  - sudo apt-get install -y python-pip
  - pip install --user Sphinx alabaster pint
  - export PATH=$HOME/.local/bin:$PATH

script:
  - make doc
  - find .
#  - mkdir -p doc/build/_downloads
#  - for v in `git tag | grep '^v'`; do  git archive -o doc/build/_downloads/smilei-${v}.tar.gz $v; done
    
install:

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: build/html
  on:
    branch: master



