os: linux

language: python

install:

git:
  depth: 9999999

before_install:
  - git fetch -t
  - pip install Sphinx travis-sphinx alabaster pint
  - export PATH=$HOME/.local/bin:$PATH

#script:
#  - travis-sphinx build -n -s doc/Sphinx
#  - mkdir -p doc/build/_downloads
#  - for v in `git tag | grep '^v'`; do  git archive -o doc/build/_downloads/smilei-${v}.tar.gz $v; done
#
#after_success:
#  - travis-sphinx deploy
#    

script:
 - make doc
 - find .
 - mkdir -p doc/build/_downloads
 - for v in `git tag | grep '^v'`; do  git archive -o doc/build/_downloads/smilei-${v}.tar.gz $v; done
 - git push origin --delete gh-pages;
 - git branch -d gh-pages;
 - git subtree push --prefix doc/build/ origin gh-pages;#    

deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GH_TOKEN
 keep-history: true
 local-dir: build/html
 on:
   branch: master



