stages:
    - make all

build:
  stage: make all
  only:
    - test_ci
  script:
    - make clean
    - make
 
#test:
#  stage: test
#  only:
#    - master
#    - develop
#  script:
#    - make clean install unit_test
#
#doc_develop:
#  stage: doc
#  only:
#    - develop
#  script:
#    - make clean install
#    - make -C docs
#
#doc_master:
#  stage: doc
#  only:
#    - master
#  script:
#    - make clean install
#    - make -C docs
#    - rsync -rL docs/documentation/html/* pyrame@llr.in2p3.fr:/home/llr/info/www/sites/pyrame/documentation
#
#web_master:
#  stage: web
#  only:
#    - master
#  script:
#    - rsync -rL exclude_from_packaging/www/* pyrame@llr.in2p3.fr:/home/llr/info/www/sites/pyrame/
#
#publish_master:
#  stage: publish
#  only:
#    - tags
#  script:
#    - make tarball
#    - scp pyrame.tgz pyrame@llr.in2p3.fr:/home/llr/info/www/sites/pyrame/pyrame_${CI_BUILD_TAG}.tgz
#    - rm pyrame.tgz
#
#uninstall:
#  stage: uninstall
#  only:
#    - master
#    - develop
#  script:
#    - make uninstall
#  when: always
